// Package teampkg builds portable, deterministic agent-team archives.
package teampkg

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	SchemaVersion          = 1
	AuthenticityUnverified = "unverified"
	ManifestFilename       = "package.yaml"
	LockFilename           = "TEAM.lock.json"
	teamDigestDomain       = "hufu.team-package.lock.v1"
)

var versionPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._+-]{0,127}$`)

// Manifest is the stable package identity stored at package.yaml.
type Manifest struct {
	SchemaVersion int    `yaml:"schema_version"`
	Name          string `yaml:"name"`
	Version       string `yaml:"version"`
	TeamManifest  string `yaml:"team_manifest"`
	Authenticity  string `yaml:"authenticity"`
}

// LockFile records one archive entry's exact authored or generated bytes.
type LockFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

// Lock is the deterministic integrity index stored at TEAM.lock.json. The
// lock file itself is intentionally excluded from Files.
type Lock struct {
	SchemaVersion int        `json:"schema_version"`
	TeamDigest    string     `json:"team_digest"`
	Files         []LockFile `json:"files"`
}

func validateVersion(version string) error {
	if !versionPattern.MatchString(version) {
		return fmt.Errorf("version %q must match %s", version, versionPattern.String())
	}
	return nil
}

func encodeManifest(manifest Manifest) ([]byte, error) {
	data, err := yaml.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("encode package manifest: %w", err)
	}
	return data, nil
}

func buildLock(files map[string][]byte) (Lock, []byte, error) {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	lock := Lock{SchemaVersion: SchemaVersion, Files: make([]LockFile, 0, len(paths))}
	for _, path := range paths {
		data := files[path]
		sum := sha256.Sum256(data)
		lock.Files = append(lock.Files, LockFile{
			Path: path, SHA256: hex.EncodeToString(sum[:]), Size: int64(len(data)),
		})
	}
	digest := sha256.New()
	_, _ = digest.Write([]byte(teamDigestDomain))
	_, _ = digest.Write([]byte{0})
	for _, file := range lock.Files {
		_, _ = digest.Write([]byte(file.Path))
		_, _ = digest.Write([]byte{0})
		_, _ = digest.Write([]byte(file.SHA256))
		_, _ = digest.Write([]byte{0})
		_, _ = digest.Write([]byte(strconv.FormatInt(file.Size, 10)))
		_, _ = digest.Write([]byte{0})
	}
	lock.TeamDigest = "sha256:" + hex.EncodeToString(digest.Sum(nil))
	data, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		return Lock{}, nil, fmt.Errorf("encode package lock: %w", err)
	}
	data = append(data, '\n')
	return lock, data, nil
}

func validateManifestIdentity(name, teamManifest, version string) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("compiled team name is empty")
	}
	if teamManifest != "team.yaml" && teamManifest != "team.yml" {
		return fmt.Errorf("unsupported team manifest %q", teamManifest)
	}
	return validateVersion(version)
}
