package main

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

var examplesFormat string

var examplesCmd = &cobra.Command{Use: "examples", Short: "Show common hufu commands from the shared command metadata", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
	if examplesFormat == "markdown" {
		return renderOperatorCommandReference(cmd.OutOrStdout())
	}
	if examplesFormat != "text" {
		return fmt.Errorf("unsupported examples format %q; use text or markdown", examplesFormat)
	}
	return renderCanonicalExamples(cmd.OutOrStdout())
}}

func init() {
	examplesCmd.Flags().StringVar(&examplesFormat, "format", "text", "Output format: text or markdown")
}

func renderCanonicalExamples(writer io.Writer) error {
	var output strings.Builder
	section := ""
	for _, example := range canonicalExamples {
		if example.Section != section {
			if section != "" {
				output.WriteByte('\n')
			}
			section = example.Section
			output.WriteString(section)
			output.WriteString(":\n")
		}
		output.WriteString("  ")
		output.WriteString(example.Argv)
		output.WriteByte('\n')
	}
	_, err := fmt.Fprint(writer, output.String())
	return err
}

func renderOperatorCommandReference(writer io.Writer) error {
	if _, err := fmt.Fprint(writer, "# Operator command reference\n\n> Status: active\n> Authority: reference\n> Verified-Commit: generated from the current command metadata\n> Supersedes: —\n> Superseded-By: —\n\n<!-- Generated by: go run ./cmd/hufu examples --format markdown -->\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(writer, "## Command groups\n\n"); err != nil {
		return err
	}
	for _, group := range commandGroups {
		commands := make([]string, len(group.Commands))
		for index, command := range group.Commands {
			commands[index] = "`hufu " + command + "`"
		}
		if _, err := fmt.Fprintf(writer, "- **%s:** %s\n", group.Title, strings.Join(commands, ", ")); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(writer, "\n## Parse-checked examples\n\n"); err != nil {
		return err
	}
	section := ""
	for _, example := range canonicalExamples {
		if example.Section != section {
			section = example.Section
			if _, err := fmt.Fprintf(writer, "### %s\n\n", section); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintf(writer, "```sh\n%s\n```\n\n", example.Argv); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(writer, "## Flag groups\n\n"); err != nil {
		return err
	}
	groups := make([]string, 0, len(cliFlagGroups))
	for name := range cliFlagGroups {
		groups = append(groups, name)
	}
	sort.Strings(groups)
	for _, name := range groups {
		flags := make([]string, len(cliFlagGroups[name]))
		for index, flag := range cliFlagGroups[name] {
			flags[index] = "`--" + flag + "`"
		}
		if _, err := fmt.Fprintf(writer, "- **%s:** %s\n", name, strings.Join(flags, ", ")); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(writer, "\n## Dynamic ID completion\n\nBash, Zsh, Fish, and PowerShell scripts generated by Cobra complete local run, branch, task, context, and proposal IDs. Queries are read-only, limited to %d results, and have a %s deadline. Task candidates require a run and stay on the selected branch; context candidates exclude private and branch-scoped records; proposal candidates require project and team. Missing, locked, or unsupported stores return no candidates. The custom Nushell exporter currently provides typed command declarations but not selector-aware dynamic IDs; it does not fall back to a cross-scope search.\n", completionResultLimit, completionQueryTimeout); err != nil {
		return err
	}
	return nil
}

var helpFlagsCmd = &cobra.Command{Use: "help-flags <group>", Short: "Show flags in a named group", Args: cobra.ExactArgs(1), RunE: runHelpFlags}

func runHelpFlags(cmd *cobra.Command, args []string) error {
	group := strings.ToLower(args[0])
	flags, ok := cliFlagGroups[group]
	if !ok {
		names := make([]string, 0, len(cliFlagGroups))
		for name := range cliFlagGroups {
			names = append(names, name)
		}
		sort.Strings(names)
		return fmt.Errorf("unknown flag group %q; available: %s", group, strings.Join(names, ", "))
	}
	root := cmd.Root()
	for _, name := range flags {
		flag := root.Flags().Lookup(name)
		if flag == nil {
			flag = root.PersistentFlags().Lookup(name)
		}
		if flag == nil {
			if run, _, err := root.Find([]string{"run"}); err == nil {
				flag = run.Flags().Lookup(name)
			}
		}
		if flag == nil {
			continue
		}
		if _, err := fmt.Fprintf(cmd.OutOrStdout(), "--%-20s %s\n", name, flag.Usage); err != nil {
			return err
		}
	}
	return nil
}
