package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedOperatorCommandReferenceIsCurrent(t *testing.T) {
	var generated bytes.Buffer
	if err := renderOperatorCommandReference(&generated); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join("..", "..", "docs", "reference", "operator-command-reference.md")
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if generated.String() != string(committed) {
		t.Fatalf("%s is stale; regenerate with `go run ./cmd/hufu examples --format markdown`", path)
	}
}

func TestCanonicalExamplesAreShellParseableAndReferenceExistingCommands(t *testing.T) {
	root := newRootCommand()
	for _, example := range canonicalExamples {
		check := exec.Command("bash", "-n", "-c", example.Argv)
		if output, err := check.CombinedOutput(); err != nil {
			t.Fatalf("example is not valid shell syntax: %s: %v\n%s", example.Argv, err, output)
		}
		fields := strings.Fields(example.Argv)
		if len(fields) < 2 || fields[0] != "hufu" {
			t.Fatalf("invalid canonical example: %q", example.Argv)
		}
		command, _, err := root.Find(fields[1:])
		if err != nil || command == root {
			t.Fatalf("example references no implemented command: %s: %v", example.Argv, err)
		}
	}
}
